export { default as gridAuto } from '@jill64/tailwind-grid-auto'
export { default as reactions } from '@jill64/tailwind-reactions'
export type { Config as PostcssConfig } from 'postcss-load-config'
export type { Config as TailwindConfig } from 'tailwindcss'
export { postcssConfig } from './postcssConfig.js'
export { tailwindConfig } from './tailwindConfig.js'
